config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :articles


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 1000}
  validates :user_id, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates :username, presence: true, length: { minimum: 3, maximum: 25 },
                       uniqueness: {case_sensetive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save {self.email = email.downcase}
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensetive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/PagesController.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # any functionality here will be available for any other controller as we inherit form this class
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :destroy, :update, :show]

  def index
    @articles = Article.all
  end

  def new
    #article demo
    @article = Article.new
  end

  def edit
  end

  def destroy
    @article.destroy
    flash[:danger] = "The article is deleted successfully!"
    redirect_to articles_path
  end

  def create
    #render plain: params[:article].inspect     #To display what is passed via params hash
    @article = Article.new(article_params)      #White list the params first
    @article.user = User.first
    if @article.save
      flash[:success] = "The article is created successfully!"     #Stays for one redirect cycle
      redirect_to article_path(@article)     #it needs the article (/id), Show action is needed
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)      #Similar way to build an article
      flash[:success] = "The article is updated successfully!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end


  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_parmas)
    if @user.save
      flash[:success] = "Welcome to Alpha-Blog #{@user.username}"
      redirect_to articles_path
    else
    render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_parmas)
      flash[:success] = "Your account has updated successfully!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_parmas
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
#helpers are used to support views only
module ApplicationHelper
  def gravatar_for (user, options={size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/views/articles/_article.html.erb
<body class="site-body site-body2 d-flex flex-column">
  <%= render 'layouts/navigation' %>
  <h1 class="text-center mt-4 head-purple">Listing All Articles</h1>
  <div class="container">
    <% obj.each do |article| %>
      <div class="row mt-4 justify-content-md-center">
        <div class="col-9">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header">
              Created by: <%= article.user.username if article.user %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: "head-purple" %></h5>
              <p class="card-text"><%= truncate(article.description, length: 300) %></p>
              <div class="article-btns">
                <%= link_to 'View', article_path(article), class:"btn btn-outline-primary round-btn my_btn" %>
                <%= link_to 'Edit', edit_article_path(article), class:"btn btn-outline-primary round-btn" %>
                <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class:"btn btn-outline-danger round-btn" %>
              </div>
            </div>
            <div class="card-footer text-muted">
              <small>
                 <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago.</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</body>

app/views/articles/_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="site-body d-flex flex-column">
    <div id="page-content">
      <%= render 'layouts/navigation' %>
      <%= render 'shared/errors' %>

      <div class='row form shadow mb-5 rounded'>
        <div class='col-md-12'>
          <%= form_for @article do |f| %>
          <h1 class='sign-text' align='center'>Create an Article</h1>
            <div class="form-group" >
              <div class="control-label col-sm-2">
                <%= f.label :title %>
              </div>
              <div class='col-sm-12'>
                <%= f.text_field :title, class: "form-control", placeholder: "Title of the article", autofocus: true %>
              </div>
            </div>
            <div class="form-group">
              <div class="control-label col-sm-2">
                <%= f.label :decription %>
              </div>
              <div class='col-sm-12'>
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of the article" %>
              </div>
            </div>
            <div class="form-group" align="center">
              <div class="col-sm-10">
                <%= f.submit class: "btn btn-lg my_active_btn"%>
              </div>
            </div>


          <% end %>
          <div class="form-group" align='center'>
            <div class="col-sm-10">
              <%= link_to '[ Cancel Request and return to articles listing ]', articles_path, class: "text-info" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="site-body d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'shared/errors' %>

    <div class='row form shadow mb-5 rounded'>
      <div class='col-md-12'>
        <%= form_for @article do |f| %>
        <h1 class='sign-text' align='center'>Edit the Article</h1>
          <div class="form-group" >
            <div class="control-label col-sm-2">
              <%= f.label :title %>
            </div>
            <div class='col-sm-12'>
              <%= f.text_field :title, class: "form-control shadow bg-white rounded", placeholder: "Title of the article", autofocus: true %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :decription %>
            </div>
            <div class='col-sm-12'>
              <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of the article" %>
            </div>
          </div>
          <div class="form-group" align="center">
            <div class="col-sm-10">
              <%= f.submit class: "btn btn-lg my_active_btn"%>
            </div>
          </div>


        <% end %>
        <div class="form-group" align='center'>
          <div class="col-sm-10">
            <%= link_to '[ Cancel Request and return to articles listing ]', articles_path, class:"text-info" %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/articles/index.html.erb
<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1 class='head' align='center'>Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<body class="site-body d-flex flex-column">
  <%= render 'layouts/navigation' %>
  <h2 class="text-center mt-4 head-purple"><%= @article.title %></h2>
  <div class="container">
    <div class="row mt-4 justify-content-md-center">
      <div class="col-9">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            Created by: <%= @article.user.username if @article.user %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <div class="article-btns">
              <%= link_to 'Edit', edit_article_path(@article), class:"btn btn-outline-primary round-btn" %>
              <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class:"btn btn-outline-danger round-btn" %>
            </div>
          </div>
          <div class="card-footer text-muted">
            <small>
               <%= time_ago_in_words(@article.created_at) %> ago, last updated: <%= time_ago_in_words(@article.updated_at) %> ago.</small>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Ahmed Ashraf", "https://www.linkedin.com/in/ahmed-ashraf-92b06912a/", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= "#{name}" %> alert_body" align="center">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name} if msg.is_a?(String)" %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="colored-navbar">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link white-text" href="#">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle white-text" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "List articles", articles_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <button class="btn btn-outline-success my-2 my-sm-0 round-btn" id="login" type="submit">Login</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- All views are served here -->
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <div id="page-content">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  </head>
  <body id="home_body" class="d-flex flex-column">
    <nav class="navbar navbar-expand-lg navbar-light" >
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link white-text" href="#">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle white-text" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "List articles", articles_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <button class="btn btn-outline-success my-2 my-sm-0 round-btn" id="login" type="submit">Login</button>
        </form>
      </div>
    </nav>
    <div class="container">
      <div id="home_jumbotron" align="center">
        <h1 class="display-4" align="center" id="welcome">Welcome to <span id="alpha-word">Alpha-Blog</span> !</h1>
        <br><p class="lead">This is an application where you can create simple articles containing
           title and description, add categories to those articles and be able to edit or delete your own.</p>
        <hr class="my-4">
        <p align="center">If you don't have an account join us now!</p>
        <%= link_to "Sign up", signup_path, class: "btn btn-lg my_btn round-btn signup-btn", align: "center" %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show alert_body" role="alert">
    <div>
      <h2>
        <%= pluralize(@article.errors.count, "error") %>
        prohibited this article from being saved
      </h2>
      <div>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class= <%= @user.new_record? ? "sign-body" : "site-body" %>>
    <div class='row form signup-frame'>
      <div class='col-md-12'>
        <%= form_for @user do |f| %>
        <h1 class="sign-text" align="center"> <%= @user.new_record? ? "Sign-up for Alpha-Blog" : "Edit your account" %> </h1>
          <div class="form-group" >
            <div class="control-label col-sm-2 signup">
              <%= f.label :username %>
            </div>
            <div class='col-sm-12'>
              <%= f.text_field :username, class: "form-control",  align: "center", placeholder: "Enter username", autofocus: true %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2 signup">
              <%= f.label :email %>
            </div>
            <div class='col-sm-12'>
              <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
            </div>
          </div>
          <div class="form-group">
            <div class="control-label col-sm-2 signup">
              <%= f.label :password %>
            </div>
            <div class='col-sm-12'>
              <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
          </div>
          <div class="form-group" align="center">
            <div class="col-sm-10">
              <%= f.submit (@user.new_record? ? "Sign-up" : "Update your account"), class: "btn btn-lg my_active_btn"%>
            </div>
          </div>
        <% end %>
        <div class="form-group" align='center'>
          <div class="col-sm-10">
            <%= link_to 'Cancel Request and return to articles listing', articles_path %>
          </div>
        </div>
      </div>
    </div>
    <% if @user.errors.any? %>
      <div class="alert alert-danger" id="alert_body" role="alert">
        <div>
          <h2>
            <%= pluralize(@user.errors.count, "errors") %>
            prohibited this article from being saved:
          </h2>
          <div>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="site-body">
    <div class='profile-frame'>
        <h1 class="sign-text" align="center"> All Alpha-Blogers</h1>
        <% @users.each do |user| %>
        <div class="article-body list-users" align="center">
          <div class="gravatar">
            <%= link_to gravatar_for(user), user_path(user) %>
          </div>
          <%= link_to user.username, user_path(user), class: "article-title name" %>
          <div class="meta-details">
            <li><small> <%= pluralize(user.articles.count, "article") if user.articles %> created. </small></li>
          </div>

        </div>
        <% end %>
        <div class="return" align='center'>
            <%= link_to 'Return to articles listing', articles_path %>
        </div>
      </div>
  </body>
</html>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="site-body">
    <div class='profile-frame'>
        <h1 class="sign-text" align="center"> <%= @user.username %>'s page</h1>
        <div class="gravatar" align="center">
          <%= gravatar_for @user, size: 150 %>
        </div>
        <h4 align="center" class="white-head"><%= @user.username %>'s articles</h4>
        <%= render 'articles/article', obj: @user.articles %>
        <div class="return" align='center'>
            <%= link_to 'Return to articles listing', articles_path %>
        </div>
      </div>
  </body>
</html>